export { default as AccommodationDetailsName } from "./AccommodationDetailsName";
export { default as AccommodationDetailsSite } from "./AccommodationDetailsSite";
export { default as AccommodationDetailsPhoneNumber } from "./AccommodationDetailsPhoneNumber";
export { default as AccommodationDetailsBedCapacity } from "./AccommodationDetailsBedCapacity";
export { default as AccommodationDetailsPricePerBed } from "./AccommodationDetailsPricePerBed";
export { default as AccommodationDetailsFood } from "./AccommodationDetailsFood";
export { default as AccommodationDetailsAccess } from "./AccommodationDetailsAccess";
export { default as AccommodationDetailsNextTo } from "./AccommodationDetailsNextTo";
export { default as AccommodationDetailsInfo } from "./AccommodationDetailsInfo";
