export * from "./accommodationsApi"; //1
export * from "./destinationsApi"; //2
export * from "./hikesApi"; //3
export * from "./commentsApi"; //4
export * from "./gpxApi"; //5
export * from "./imagesApi"; //6
export * from "./trailsApi"; //7
export * from "./usersApi"; //8
export * from "./utilitiesApi"; //9
